# ISOM5240 Assignment Ou Zhiyong
# import part
import io
import re

import streamlit as st
from PIL import Image
from transformers import pipeline
from gtts import gTTS


# ---------------------------------------------------------
# Page configuration is what we can see on the web page heading
# ---------------------------------------------------------
st.set_page_config(
    page_title="Magic Story Maker - ISOM5240",
    page_icon="📖",
    layout="centered"
)


# ---------------------------------------------------------
# Load Hugging Face models
# ---------------------------------------------------------
@st.cache_resource
def load_captioning_model():
    """
    Load the BLIP image-captioning model.

    The model analyzes the uploaded image and produces
    a short description of what is visible.
    """
    return pipeline(
        "image-to-text",
        model="Salesforce/blip-image-captioning-base"
    )


@st.cache_resource
def load_story_model():
    """
    Load the Hugging Face text generation model.

    FLAN-T5 is used to transform the image caption
    into a short children's story.
    """
    return pipeline(
        "text2text-generation",
        model="google/flan-t5-small"
    )


# ---------------------------------------------------------
# Image captioning Function
# ---------------------------------------------------------
def generate_image_caption(image, captioner):
    """
    Generate a description of the uploaded image.

    Parameters:
        image: PIL image
        captioner: Hugging Face image-captioning pipeline

    Returns:
        A string containing the image caption.
    """

    result = captioner(
        image,
        max_new_tokens=40
    )

    caption = result[0]["generated_text"]

    return caption.strip()


# ---------------------------------------------------------
# Story generation Function
# ---------------------------------------------------------
def generate_story(caption, story_generator):
    """
    Generate a child-friendly story based on the image caption.

    The story is requested to be between 50 and 100 words.
    """

    prompt = f"""
Write a fun, gentle and imaginative children's story
for children aged 3 to 10.

The story must be based on this image description:

{caption}

Requirements:
- Write between 50 and 100 words.
- Use simple language.
- Give the story a beginning, middle and ending.
- Make it cheerful and imaginative.
- Avoid violence, frightening situations and inappropriate topics.
- Do not mention that the story was generated by a computer.
- Do not use a title.
"""

    result = story_generator(
        prompt,
        max_new_tokens=140,
        do_sample=True,
        temperature=0.8,
        top_p=0.9
    )

    story = result[0]["generated_text"].strip()

    return enforce_word_limit(story)


# ---------------------------------------------------------
# Word-count helper Function
# ---------------------------------------------------------
def count_words(text):
    """
    Count the number of words in a text.
    """
    return len(text.split())


def enforce_word_limit(text, minimum=50, maximum=100):
    """
    Ensure that the generated story is no longer than
    the assignment's 100-word maximum.

    If the model produces more than 100 words,
    the story is shortened at the nearest sentence boundary.
    """

    words = text.split()

    if len(words) <= maximum:
        return text

    shortened_text = " ".join(words[:maximum])

    # Try to finish at the last complete sentence.
    sentences = re.split(r"(?<=[.!?])\s+", shortened_text)

    if len(sentences) > 1:
        shortened_text = " ".join(sentences[:-1])

    return shortened_text.strip()


# ---------------------------------------------------------
# Text-to-speech Function
# ---------------------------------------------------------
def generate_audio(story):
    """
    Convert the generated story into an MP3 audio file
    using Google Text-to-Speech.
    """

    audio_buffer = io.BytesIO()

    tts = gTTS(
        text=story,
        lang="en",
        slow=False
    )

    tts.write_to_fp(audio_buffer)

    audio_buffer.seek(0)

    return audio_buffer


# ---------------------------------------------------------
# Main Streamlit application
# ---------------------------------------------------------
def main():

    # Application title
    st.title("📖✨ Magic Story Maker")

    st.write(
        "Upload a picture and let AI turn it into "
        "a fun children's story!"
    )

    st.info(
        "Designed for children aged 3–10. "
        "Stories are kept short, simple and friendly."
    )

    # Image uploader
    uploaded_file = st.file_uploader(
        "📷 Upload an image",
        type=["jpg", "jpeg", "png"]
    )

    if uploaded_file is not None:

        # Open uploaded image
        image = Image.open(uploaded_file).convert("RGB")

        # Display image
        st.image(
            image,
            caption="Your uploaded picture",
            use_container_width=True
        )

        # Generate button
        if st.button(
            "✨ Create My Story",
            type="primary"
        ):

            try:

                # Load models
                with st.spinner(
                    "🔍 Looking at your picture..."
                ):
                    captioner = load_captioning_model()

                    caption = generate_image_caption(
                        image,
                        captioner
                    )

                # Display caption
                st.subheader("🔍 What I see")

                st.write(caption)

                # Generate story
                with st.spinner(
                    "📖 Writing your magical story..."
                ):
                    story_generator = load_story_model()

                    story = generate_story(
                        caption,
                        story_generator
                    )

                # Display story
                st.subheader("📖 Your Story")

                st.write(story)

                # Display word count
                word_count = count_words(story)

                st.caption(
                    f"Story length: {word_count} words"
                )

                # Warn if word count is outside assignment range
                if word_count < 50:
                    st.warning(
                        "The generated story contains fewer "
                        "than 50 words. You may regenerate it."
                    )

                elif word_count > 100:
                    st.warning(
                        "The generated story contains more "
                        "than 100 words."
                    )

                else:
                    st.success(
                        "✓ Story meets the 50–100 word requirement."
                    )

                # Generate audio
                with st.spinner(
                    "🔊 Creating the audio story..."
                ):
                    audio_file = generate_audio(story)

                # Audio player
                st.subheader("🔊 Listen to Your Story")

                st.audio(
                    audio_file,
                    format="audio/mp3"
                )

                # Download button
                st.download_button(
                    label="⬇️ Download Story Audio",
                    data=audio_file.getvalue(),
                    file_name="magic_story.mp3",
                    mime="audio/mp3"
                )

            except Exception as error:

                st.error(
                    "Sorry, something went wrong while "
                    "creating the story."
                )

                st.exception(error)

    else:

        st.write(
            "👆 Upload a picture above to begin!"
        )


# ---------------------------------------------------------
# Program entry point
# ---------------------------------------------------------
if __name__ == "__main__":
    main()
